apm install atom-beautify
apm install autocomplete-paths
apm install color-picker
apm install file-icons
apm install highlight-line
apm install highlight-selected
apm install line-ending-converter
apm install markdown-preview-enhanced
apm install minimap
apm install pigments
